This is an example from another project where I use flask and grapene.  The problem is the same with anything using the current version of
flask_graphql.  The queries would be different for whatever you are exposing with grapinator.  I am currently brute forcing the change
below in the flask_graphql library when setup.py is run.  

Use burpsuite community

Download that. Start a temporary project. Go to the “repeater” tab. In the top right of that tab edit the “target” with the server, port, and https options. Then copy and paste the full POST request example I gave below into the “request” box. Hit “Go”

For localhost

POST /asset/gql? HTTP/1.1
Host: localhost:18443
Connection: close
Content-Length: 169
Accept: application/json
Origin: http://localhost:18443
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
DNT: 1
Content-Type: application/json
Accept-Language: en-US,en;q=0.9
Cookie: _ga=GA1.2.2098746022.1551373676; nrelGovGA=GA1.2.1506305852.1554131201; cl___cav=true; cl__caz=1.direct%7C%7C%7C%7C; cl__calts=; cl__userid=i%3A0%23.w%7Cnrel_nt%5Csthew; cl_s=440909995.619826855; cl_7b8c7_lveid=3009482; cl_149e8_lveid=3009547; cl__cauid=a4a04204a1.1554148975296.1.7; cl__pts=7; cl_sf=sf_947; cl_LastValueSearch=3200320; cl_lvu=https%3A%2F%2Fsp2013.nrel.gov%2FPages%2Fresults.aspx%3Fk%3Dcyber; cl__cass=1.1.1%2C6.3.1%2C2.2.1; cl_867f4_lveid=3200325; cl_lveid=3200325; cl_867f4_lseid=3200326; cl_lseid=3200326; _gid=GA1.2.515111769.1560789522; nrelGovGA_gid=GA1.2.1616750017.1560791317

{"query":"{\n  asset(center_number: \"ý or 1=1 --") {\n    edges {\n      node {\n        center_number\n      }\n    }\n  }\n}\n","variables":null,"operationName":null}

For intci


POST /asset/gql? HTTP/1.1
Host: intci.nrel.gov:18443
Connection: close
Content-Length: 169
Accept: application/json
Origin: https://intci.nrel.gov:18443
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
DNT: 1
Content-Type: application/json
Accept-Language: en-US,en;q=0.9
Cookie: _ga=GA1.2.2098746022.1551373676; nrelGovGA=GA1.2.1506305852.1554131201; cl___cav=true; cl__caz=1.direct%7C%7C%7C%7C; cl__calts=; cl__userid=i%3A0%23.w%7Cnrel_nt%5Csthew; cl_s=440909995.619826855; cl_7b8c7_lveid=3009482; cl_149e8_lveid=3009547; cl__cauid=a4a04204a1.1554148975296.1.7; cl__pts=7; cl_sf=sf_947; cl_LastValueSearch=3200320; cl_lvu=https%3A%2F%2Fsp2013.nrel.gov%2FPages%2Fresults.aspx%3Fk%3Dcyber; cl__cass=1.1.1%2C6.3.1%2C2.2.1; cl_867f4_lveid=3200325; cl_lveid=3200325; cl_867f4_lseid=3200326; cl_lseid=3200326; _gid=GA1.2.515111769.1560789522; nrelGovGA_gid=GA1.2.1616750017.1560791317
 
{"query":"{\n  asset(center_number: \"ý or 1=1 --") {\n    edges {\n      node {\n        center_number\n      }\n    }\n  }\n}\n","variables":null,"operationName":null}

Produces the following stacktrace:

2019-06-24 13:49:02,591 - flask.app - ERROR - Exception on /project/gql [POST]
Traceback (most recent call last):
File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
response = self.full_dispatch_request()
File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
    File "/opt/app-root/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
     return cors_after_request(app.make_response(f(*args, **kwargs)))
   File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
      reraise(exc_type, exc_value, tb)
    File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
      raise value
    File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
      rv = self.dispatch_request()
    File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
      return self.view_functions[rule.endpoint](**req.view_args)
    File "/opt/app-root/lib/python3.6/site-packages/flask/views.py", line 88, in view
      return self.dispatch_request(*args, **kwargs)
    File "/opt/app-root/lib/python3.6/site-packages/flask_graphql/graphqlview.py", line 68, in dispatch_request
      data = self.parse_body()
    File "/opt/app-root/lib/python3.6/site-packages/flask_graphql/graphqlview.py", line 136, in parse_body
      return load_json_body(request.data.decode('utf8'))
   | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 39: invalid start byte

Offending line 136 in /opt/app-root/lib/python3.6/site-packages/flask_graphql/graphqlview.py

tmp fix is replace

return load_json_body(request.data.decode('utf8'))

with

try:
    return load_json_body(request.data.decode('utf8'))
except UnicodeDecodeError:
    return load_json_body(request.data.decode('utf8', "backslashreplace"))

But this is vendor supplied code :-(
